### ISSUE TITLE
Add MarkGhebrial/advent-of-code-2024

### ISSUE THREAD

**Issue by MarkGhebrial** [CodSpeedHQ/Advent#18]
### Repository URL

https://github.com/MarkGhebrial/advent-of-code-2024.git

**Comment by qsantos** [comment]
I think the [GitHub workflow](https://github.com/CodSpeedHQ/Advent/actions/runs/12103214150/job/33745129424) does not like your URL ending in `.git`. You better close this issue and open a new one with `https://github.com/MarkGhebrial/advent-of-code-2024` instead. Make sure **not** to have a trailing slash either.

**Comment by MarkGhebrial** [comment]
Gotcha, thanks
