### ISSUE TITLE
My entry is missing for day 3

### ISSUE THREAD

**Issue by technotive** [CodSpeedHQ/Advent#184]
But day 1, 2 and 4 did appear on the scoreboard.
I likely won't score any point but I would like to be on the board for comparison and completeness sake!
Can you help me investigate why my day 3 did not register?

**Comment by adriencaccia** [comment]
Hey, it seems that at the time of the run your day 3 was missing/misconfigured: https://github.com/CodSpeedHQ/Advent/actions/runs/12164645220/job/33926891233

**Comment by adriencaccia** [comment]
It seems you have the [same issue for `day5`](https://github.com/technotive/advent_2024/blob/main/src/day5.rs), you will need to fix before today's run in 3h for the run to work!

**Comment by technotive** [comment]
That you for looking into it! Unfortunately I have other obligations for the coming hours. I may not make it but I will try.

All the best,
Conno

Sent from Proton Mail Android

-------- Original Message --------
