### ISSUE TITLE
Change toolchain to nightly for nedmv/rusty-advent

### ISSUE THREAD

**Issue by nedmv** [CodSpeedHQ/Advent#216]
### Repository URL

https://github.com/nedmv/rusty-advent

### Toolchain version

nightly

**Comment by nedmv** [comment]
Curiously, it worked that way in the past (#157). Guess that some additional checks were added.

**Comment by adriencaccia** [comment]
> Curiously, it worked that way in the past (#157). Guess that some additional checks were added.

Yeah it worked but it was creating a duplicate entry for the repository 😕

I changed your toolchain in b7db0057ecf9b00a472684e1825d4fa5a0840e8f
